# -------------------------------------------------------------------
# gen_rc.cmake  —  auto‑generate assets.rc with RCDATA entries
# Invoked by CMake via:
#   cmake -DASSETS_LIST="...;..." -DOUT_FILE=... -P gen_rc.cmake
# -------------------------------------------------------------------

if(NOT DEFINED ASSETS_LIST)
    message(FATAL_ERROR "ASSETS_LIST not provided")
endif()
if(NOT DEFINED OUT_FILE)
    message(FATAL_ERROR "OUT_FILE not provided")
endif()

# Write header
file(WRITE "${OUT_FILE}" "/* Auto‑generated by gen_rc.cmake — DO NOT EDIT */\n")

set(id 1000)
foreach(path IN LISTS ASSETS_LIST)
    get_filename_component(fname "${path}" NAME)
    # Windows RC requires backslashes escaped; use full native path
    file(TO_NATIVE_PATH "${path}" native)

    file(APPEND "${OUT_FILE}" "/* ${fname} */\n")
    file(APPEND "${OUT_FILE}" "${id} RCDATA \"${native}\"\n")
    math(EXPR id "${id} + 1")
endforeach()
