# ---------------------------------------------------------------------------
#  gen_rc.cmake  —  Generate a Windows resource script (assets.rc)
# ---------------------------------------------------------------------------
#  Invoked at *configure* time by CMakeLists.txt :
#      cmake -DASSETS_LIST="<semicolon‑list>" -DOUT_FILE=<path> -P gen_rc.cmake
#
#  Variables expected (passed via -D):
#    ASSETS_LIST   : semicolon‑separated absolute paths of files to embed
#    OUT_FILE      : destination .rc file to write
#
#  Behaviour:
#    • Assigns incremental numeric IDs starting at 1000
#    • Emits one "RCDATA" line per file
#    • Adds a comment with the original filename for readability
# ---------------------------------------------------------------------------

if(NOT DEFINED ASSETS_LIST OR "${ASSETS_LIST}" STREQUAL "")
    message(FATAL_ERROR "gen_rc.cmake: ASSETS_LIST is empty — nothing to embed.")
endif()

if(NOT DEFINED OUT_FILE)
    message(FATAL_ERROR "gen_rc.cmake: OUT_FILE not specified.")
endif()

file(WRITE "${OUT_FILE}" "/* Auto‑generated by gen_rc.cmake — DO NOT EDIT */\n\n")

set(id 1000)
foreach(path IN LISTS ASSETS_LIST)
    # Ensure the file exists — helps catch typos early.
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "gen_rc.cmake: Asset not found: ${path}")
    endif()

    get_filename_component(fname "${path}" NAME)
    file(APPEND "${OUT_FILE}" "/* ${fname} */\n")
    file(APPEND "${OUT_FILE}" "${id} RCDATA \"${path}\"\n")
    math(EXPR id "${id} + 1")
endforeach()
